# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20180119_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='product_image',
            field=models.ImageField(upload_to='media', verbose_name='Upload Image'),
        ),
    ]
